/*
 * This file is generated by jOOQ.
 */
package com.nutrymaco.parser.model.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vacancy_2020_11 implements Serializable {

    private static final long serialVersionUID = 1404750334;

    private Integer id;
    private String  name;
    private String  description;
    private String  companyName;
    private String  city;
    private Date    created;
    private Integer salaryFrom;
    private Integer salaryTo;
    private String  currency;
    private Integer experienceFrom;
    private Integer experienceTo;
    private String  url;

    public Vacancy_2020_11() {}

    public Vacancy_2020_11(Vacancy_2020_11 value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.companyName = value.companyName;
        this.city = value.city;
        this.created = value.created;
        this.salaryFrom = value.salaryFrom;
        this.salaryTo = value.salaryTo;
        this.currency = value.currency;
        this.experienceFrom = value.experienceFrom;
        this.experienceTo = value.experienceTo;
        this.url = value.url;
    }

    public Vacancy_2020_11(
        Integer id,
        String  name,
        String  description,
        String  companyName,
        String  city,
        Date    created,
        Integer salaryFrom,
        Integer salaryTo,
        String  currency,
        Integer experienceFrom,
        Integer experienceTo,
        String  url
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.companyName = companyName;
        this.city = city;
        this.created = created;
        this.salaryFrom = salaryFrom;
        this.salaryTo = salaryTo;
        this.currency = currency;
        this.experienceFrom = experienceFrom;
        this.experienceTo = experienceTo;
        this.url = url;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Integer getSalaryFrom() {
        return this.salaryFrom;
    }

    public void setSalaryFrom(Integer salaryFrom) {
        this.salaryFrom = salaryFrom;
    }

    public Integer getSalaryTo() {
        return this.salaryTo;
    }

    public void setSalaryTo(Integer salaryTo) {
        this.salaryTo = salaryTo;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Integer getExperienceFrom() {
        return this.experienceFrom;
    }

    public void setExperienceFrom(Integer experienceFrom) {
        this.experienceFrom = experienceFrom;
    }

    public Integer getExperienceTo() {
        return this.experienceTo;
    }

    public void setExperienceTo(Integer experienceTo) {
        this.experienceTo = experienceTo;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vacancy_2020_11 (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(companyName);
        sb.append(", ").append(city);
        sb.append(", ").append(created);
        sb.append(", ").append(salaryFrom);
        sb.append(", ").append(salaryTo);
        sb.append(", ").append(currency);
        sb.append(", ").append(experienceFrom);
        sb.append(", ").append(experienceTo);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
