/*
 * This file is generated by jOOQ.
 */
package com.nutrymaco.parser.model;


import com.nutrymaco.parser.model.tables.Vacancy;
import com.nutrymaco.parser.model.tables.Vacancy_2020_10;
import com.nutrymaco.parser.model.tables.Vacancy_2020_11;
import com.nutrymaco.parser.model.tables.Vacancy_2020_12;
import com.nutrymaco.parser.model.tables.records.VacancyRecord;
import com.nutrymaco.parser.model.tables.records.Vacancy_2020_10Record;
import com.nutrymaco.parser.model.tables.records.Vacancy_2020_11Record;
import com.nutrymaco.parser.model.tables.records.Vacancy_2020_12Record;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>parser_service</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<VacancyRecord, Integer> IDENTITY_VACANCY = Identities0.IDENTITY_VACANCY;
    public static final Identity<Vacancy_2020_10Record, Integer> IDENTITY_VACANCY_2020_10 = Identities0.IDENTITY_VACANCY_2020_10;
    public static final Identity<Vacancy_2020_11Record, Integer> IDENTITY_VACANCY_2020_11 = Identities0.IDENTITY_VACANCY_2020_11;
    public static final Identity<Vacancy_2020_12Record, Integer> IDENTITY_VACANCY_2020_12 = Identities0.IDENTITY_VACANCY_2020_12;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<VacancyRecord, Integer> IDENTITY_VACANCY = Internal.createIdentity(Vacancy.VACANCY, Vacancy.VACANCY.ID);
        public static Identity<Vacancy_2020_10Record, Integer> IDENTITY_VACANCY_2020_10 = Internal.createIdentity(Vacancy_2020_10.VACANCY_2020_10, Vacancy_2020_10.VACANCY_2020_10.ID);
        public static Identity<Vacancy_2020_11Record, Integer> IDENTITY_VACANCY_2020_11 = Internal.createIdentity(Vacancy_2020_11.VACANCY_2020_11, Vacancy_2020_11.VACANCY_2020_11.ID);
        public static Identity<Vacancy_2020_12Record, Integer> IDENTITY_VACANCY_2020_12 = Internal.createIdentity(Vacancy_2020_12.VACANCY_2020_12, Vacancy_2020_12.VACANCY_2020_12.ID);
    }
}
