/*
 * This file is generated by jOOQ.
 */
package com.nutrymaco.parser.model;


import com.nutrymaco.parser.model.tables.Vacancy;
import com.nutrymaco.parser.model.tables.Vacancy_2020_10;
import com.nutrymaco.parser.model.tables.Vacancy_2020_11;
import com.nutrymaco.parser.model.tables.Vacancy_2020_12;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParserService extends SchemaImpl {

    private static final long serialVersionUID = 1045777149;

    /**
     * The reference instance of <code>parser_service</code>
     */
    public static final ParserService PARSER_SERVICE = new ParserService();

    /**
     * The table <code>parser_service.vacancy</code>.
     */
    public final Vacancy VACANCY = com.nutrymaco.parser.model.tables.Vacancy.VACANCY;

    /**
     * The table <code>parser_service.vacancy_2020_10</code>.
     */
    public final Vacancy_2020_10 VACANCY_2020_10 = com.nutrymaco.parser.model.tables.Vacancy_2020_10.VACANCY_2020_10;

    /**
     * The table <code>parser_service.vacancy_2020_11</code>.
     */
    public final Vacancy_2020_11 VACANCY_2020_11 = com.nutrymaco.parser.model.tables.Vacancy_2020_11.VACANCY_2020_11;

    /**
     * The table <code>parser_service.vacancy_2020_12</code>.
     */
    public final Vacancy_2020_12 VACANCY_2020_12 = com.nutrymaco.parser.model.tables.Vacancy_2020_12.VACANCY_2020_12;

    /**
     * No further instances allowed
     */
    private ParserService() {
        super("parser_service", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.VACANCY_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Vacancy.VACANCY,
            Vacancy_2020_10.VACANCY_2020_10,
            Vacancy_2020_11.VACANCY_2020_11,
            Vacancy_2020_12.VACANCY_2020_12);
    }
}
