/*
 * This file is generated by jOOQ.
 */
package com.nutrymaco.parser.model;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in parser_service
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>parser_service.vacancy_id_seq</code>
     */
    public static final Sequence<Integer> VACANCY_ID_SEQ = new SequenceImpl<Integer>("vacancy_id_seq", ParserService.PARSER_SERVICE, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
