/*
 * This file is generated by jOOQ.
 */
package com.nutrymaco.parser.model;


import com.nutrymaco.parser.model.tables.Vacancy;
import com.nutrymaco.parser.model.tables.Vacancy_2020_10;
import com.nutrymaco.parser.model.tables.Vacancy_2020_11;
import com.nutrymaco.parser.model.tables.Vacancy_2020_12;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in parser_service
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>parser_service.vacancy</code>.
     */
    public static final Vacancy VACANCY = Vacancy.VACANCY;

    /**
     * The table <code>parser_service.vacancy_2020_10</code>.
     */
    public static final Vacancy_2020_10 VACANCY_2020_10 = Vacancy_2020_10.VACANCY_2020_10;

    /**
     * The table <code>parser_service.vacancy_2020_11</code>.
     */
    public static final Vacancy_2020_11 VACANCY_2020_11 = Vacancy_2020_11.VACANCY_2020_11;

    /**
     * The table <code>parser_service.vacancy_2020_12</code>.
     */
    public static final Vacancy_2020_12 VACANCY_2020_12 = Vacancy_2020_12.VACANCY_2020_12;
}
